# Generated by Django 5.0 on 2024-01-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='phone_num',
            new_name='phone',
        ),
    ]
